language: java

jdk:
  - oraclejdk8

before_script:
  - (cd $HOME/try_cache && find . -name '*.zlc' -print | cpio -pvdumB /)
  - (cd $HOME/try_cache && find . -name '*.graph' -print | cpio -pvdumB /)

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "M0bjPTMwinz0uXN6qjXcpyfvhz/YX9W7ty4RdV90jMU8ZJxSdGdKXRy1N0TsMO8ciOQ2fryE/FpiX+arrphnVvqUmGBh386lGvj1rhgrVqXNqlGE23cQpzHsQ0nNqTGIxnoE4dmJF3PjWoYG+B4WbFsSb3PB7sEjpLq7klqGeHk="
    - secure: "iL5BdYAmMaEDRKxNx1d9Zxn0tfJhCzXBGUvn+p7QGeQDUSVCdCc8cXS4ePbRj0401pK20nK1OouIi0lLP+z0QpZY6RrKIEncGOZeSFPQbS/vnZ7niCYJQdXCZ/GOlYUkAW2AsQl5bzzHYbHKX/TVgTuO3iFlbyeoZZuIjD3VaiM="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/try_cache

before_cache:
  - find $TRAVIS_BUILD_DIR -name '*.zlc' -print | cpio -pvdumB $HOME/try_cache
  - find $TRAVIS_BUILD_DIR -name '*.graph' -print | cpio -pvdumB $HOME/try_cache
